# Workflow for deploying from main branch to /hanabi-tracker
name: Deploy to GitHub Pages (Production)

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-production"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: "https://jparkhouse.github.io/hanabi-tracker"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set Environment for Production
        run: cp .env.production .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug - List Dist Contents
        run: ls -l dist

      - name: Save Build Output
        run: mv dist ../dist-production

      - name: Discard Local Changes
        run: git reset --hard

      - name: Checkout gh-pages Branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *

      - name: Restore Build Output
        run: mv ../dist-production/* .

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m 'Deploy to GitHub Pages from main branch'
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

